name: Airdrops
version: '${project.version}'
main: io.paradaux.airdrops.Airdrops
api-version: 1.18
commands:
  airdrop:
    description: Airdrop Command
    usage: /airdrop <trigger/tp>
    permission: airdrop.command